[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/admin"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
